name: go_router
version: 3.1.1
repository: https://github.com/jamov/packages/tree/main/packages/go_router
description: go_router but allow case-sensitive parameters

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  collection: ^1.15.0
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  logging: ^1.0.0
  meta: ^1.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
